version: "3.8"

services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile.db
    container_name: bd-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PQC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./PQC.sql:/docker-entrypoint-initdb.d/PQC.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/PQC
    volumes:
      - ./fontes/backend:/app

volumes:
  postgres_data: