version: "3.8"

services:
  postgres:
    build: .
    container_name: bd-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PQC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./PQC.sql:/docker-entrypoint-initdb.d/PQC.sql

volumes:
  postgres_data:
